language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha ./test/*.js --report lcovonly -- -R spec; rm -rf ./test/tmp && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
