#!/usr/bin/env node
var fs = require('fs');

var die = function (msg) {
    console.error(msg);
    process.exit(1);
};

var docker = function(spaniel) {
    var content = '#\n#   generated by DockerSpaniel\n#';
    content += '\nFROM '+spaniel.from;
    content += '\nMAINTAINER '+spaniel.maintainer+'\n'; 
    var numSteps = spaniel.steps.length;
    var step = undefined;
    for (var i = 0; i < numSteps; i++) {
        step = spaniel.steps[i];
        if (step.comment || step.newline) { content += '\n'; }
        if (step.comment) { content += '# '+step.comment+'\n'; }
        content += step.instruction.toUpperCase()+' ';
        content += step.arguments+'\n';
    }
    fs.writeFile('./Dockerfile', content, function(err) {
        if(err) { die('Could not write to Dockerfile: '+err); }
        console.log('Dockerfile generated.');
        process.exit(0);
    });
};

var main = function () {
    fs.readFile('./Spanielfile', 'utf8', function (err, data) {
        if (err) { die('Could not read Spanielfile: '+err); }
        var spaniel = undefined;
        try { spaniel = JSON.parse(data); }
        catch (e) { die('Spanielfile is not valid JSON: '+e); }
        docker(spaniel);
    });
};

main();
